<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Cosmos.EventDriven.Abstractions" Version="2.3.1" />
  </ItemGroup>

  <ItemGroup>
    <InternalsVisibleTo Include="Bitakora.ControlAsistencia.Contracts.Tests" />
  </ItemGroup>

  <ItemGroup>
    <Folder Include="ControlHoras\ValueObjects\" />
    <Folder Include="Empleados\ValueObjects\" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Bitakora.ControlAsistencia.PublicEvents\Bitakora.ControlAsistencia.PublicEvents.csproj" />
  </ItemGroup>

</Project>
